export const screenNames = {
    authstartup:"authstartuppage",
    login:"loginpage",
    signup:"signuppage",
    resetpassword:"resetpasswordpage",
    authflow:"authflow",
    homeflow:"homeflow",
    onboarding:"onboarding",
    home:"home",
    search:"search",
    properties:"properties",
    notification:"notification",
    profile:"profile",
    bottomflow:"bottomflow",
    propertiesDetail:"propertiesDetail",
    confirmBookingPage:"confirmBookingPage",
    addPropertyPage:"addPropertyPage",
    propsFlow: "propsFLow",
    paymentPage:"paymentPage",
    updatePage:"updatePage"
}